site_name: Stilum
repo_name: Stilum
repo_url: https://github.com/isiosis/stilum
site_description: Documentation for Stilum; A simple terminal output styler for kotlin.
site_author: isiosis
copyright: Copyright &copy; 2025 isiosis
theme: readthedocs

nav:
  - 'Getting Started': getting_started.md
  - 'Changelog': changelog.md